pipeline {
    agent any

    tools {
        // Use a custom Maven installation (defined in Jenkins Global Tool Configuration)
        maven "Maven"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Use the 'tool' step to ensure Maven is available in the PATH
                    def mvnHome = tool name: 'Maven', type: 'maven'
                    sh "${mvnHome}/bin/mvn -B -DskipTests clean package"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Use the 'tool' step to ensure Maven is available in the PATH
                    def mvnHome = tool name: 'Maven', type: 'maven'
                    sh "${mvnHome}/bin/mvn test"
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }

    post {
        failure {
            // Add post-failure steps if needed
            echo 'Pipeline failed!'
        }
    }
}
